import { dayOffset, today } from "./dates"
import type {
  Area,
  AreaVisit,
  Blocker,
  Decision,
  Defect,
  Observation,
  Person,
  Photo,
  ProjectState,
  Task,
  Tour,
  ActivityLog,
} from "./types"

/* -------------------------------------------------------------- areas ---- */

function buildAreas(): Area[] {
  const areas: Area[] = []
  let order = 1

  for (const n of [3, 2, 1]) {
    areas.push({
      id: `b${n}`,
      name: `מרתף ${n}`,
      zone: "basement",
      level: -n,
      wing: null,
      routeOrder: order++,
    })
  }
  areas.push(
    { id: "g-e", name: "קומת קרקע - מזרח", zone: "ground", level: 0, wing: "east", routeOrder: order++ },
    { id: "g-w", name: "קומת קרקע - מערב", zone: "ground", level: 0, wing: "west", routeOrder: order++ },
  )
  // route: up the east wing, roof, then down the west wing
  for (let f = 1; f <= 7; f++) {
    areas.push({
      id: `f${f}-e`,
      name: `קומה ${f} - מזרח`,
      zone: "floor",
      level: f,
      wing: "east",
      routeOrder: order++,
    })
  }
  areas.push({ id: "roof", name: "גג", zone: "roof", level: 8, wing: null, routeOrder: order++ })
  for (let f = 7; f >= 1; f--) {
    areas.push({
      id: `f${f}-w`,
      name: `קומה ${f} - מערב`,
      zone: "floor",
      level: f,
      wing: "west",
      routeOrder: order++,
    })
  }
  areas.push(
    { id: "facade", name: "חזיתות", zone: "facade", level: 9, wing: null, routeOrder: order++ },
    { id: "ext", name: "פיתוח חוץ", zone: "external", level: 9, wing: null, routeOrder: order++ },
  )
  return areas
}

/* ------------------------------------------------------------- people ---- */

const people: Person[] = [
  { id: "me", name: "אני", group: "me", role: "מנהל פרויקט" },
  { id: "p-yossi", name: "יוסי", group: "team", role: "מנהל עבודה", phone: "052-4410021" },
  { id: "p-ahmad", name: "אחמד", group: "team", role: "עובד כללי", phone: "054-8820117" },
  { id: "p-david", name: "דוד", group: "team", role: "עובד כללי", phone: "050-7719043" },
  {
    id: "c-cohen",
    name: "א. כהן ריצוף",
    group: "contractor",
    role: "קבלן ריצוף",
    trade: "ריצוף",
    phone: "052-3390188",
  },
  {
    id: "c-elec",
    name: "חשמל הצפון",
    group: "contractor",
    role: "קבלן חשמל",
    trade: "חשמל",
    phone: "053-7742290",
  },
  {
    id: "c-alum",
    name: "אלומיניום פסגות",
    group: "contractor",
    role: "קבלן אלומיניום",
    trade: "אלומיניום",
    phone: "054-6612380",
  },
  {
    id: "c-plumb",
    name: "אינסטלציה לוי",
    group: "contractor",
    role: "קבלן אינסטלציה",
    trade: "אינסטלציה",
    phone: "052-9903471",
  },
  {
    id: "c-paint",
    name: "צבעי המרכז",
    group: "contractor",
    role: "קבלן צבע",
    trade: "צבע",
    phone: "058-4471109",
  },
  {
    id: "c-gypsum",
    name: "גבס פרויקטים",
    group: "contractor",
    role: "קבלן גבס",
    trade: "גבס",
    phone: "050-3318827",
  },
  {
    id: "c-doors",
    name: "דלתות ישראל",
    group: "contractor",
    role: "ספק דלתות ומשקופים",
    trade: "נגרות",
    phone: "053-2214498",
  },
]

/* ------------------------------------------------------------- photos ---- */

const photos: Photo[] = [
  {
    id: "ph-1",
    areaId: "f4-e",
    date: dayOffset(-1),
    time: "08:24",
    caption: "ריצוף דירה 402 – הושלם כמחצית השטח",
    url: "/site/tiling.png",
    tourId: "t-1",
    pairKey: "402-tiling",
    stage: "before",
  },
  {
    id: "ph-2",
    areaId: "f4-e",
    date: today(),
    time: "08:31",
    caption: "ריצוף דירה 402 – התקדמות מאז אתמול",
    url: "/site/tiling.png",
    tourId: "t-2",
    pairKey: "402-tiling",
    stage: "after",
  },
  {
    id: "ph-3",
    areaId: "f5-w",
    date: dayOffset(-1),
    time: "08:47",
    caption: "נקודות חשמל בקיר סלון – טרם הושלמו",
    url: "/site/electrical.png",
    tourId: "t-1",
  },
  {
    id: "ph-4",
    areaId: "b2",
    date: dayOffset(-4),
    time: "08:12",
    caption: "רטיבות בחדר משאבות – כתם מתפשט",
    url: "/site/pumproom.png",
    tourId: "t-0",
    defectId: "d-1",
    pairKey: "pump-damp",
    stage: "before",
  },
  {
    id: "ph-5",
    areaId: "b2",
    date: dayOffset(-1),
    time: "08:09",
    caption: "רטיבות בחדר משאבות – ללא שינוי",
    url: "/site/pumproom.png",
    tourId: "t-1",
    defectId: "d-1",
    pairKey: "pump-damp",
    stage: "after",
  },
  {
    id: "ph-6",
    areaId: "facade",
    date: dayOffset(-1),
    time: "09:15",
    caption: "חזית מערבית – פתחים ללא אלומיניום",
    url: "/site/facade.png",
    tourId: "t-1",
  },
  {
    id: "ph-7",
    areaId: "f6-w",
    date: dayOffset(-1),
    time: "08:52",
    caption: "פתח דלת ללא משקוף – עוצר צבע",
    url: "/site/doorframes.png",
    tourId: "t-1",
  },
  {
    id: "ph-8",
    areaId: "f3-e",
    date: dayOffset(-2),
    time: "08:38",
    caption: "מסדרון – גבס בהתקנה",
    url: "/site/drywall.png",
    tourId: "t-0",
  },
  {
    id: "ph-9",
    areaId: "ext",
    date: dayOffset(-1),
    time: "09:28",
    caption: "פיתוח חוץ – התחלת אבני שפה",
    url: "/site/earthworks.png",
    tourId: "t-1",
  },
  {
    id: "ph-10",
    areaId: "f2-e",
    date: dayOffset(-2),
    time: "08:20",
    caption: "דירה 201 – צבע יסוד הושלם",
    url: "/site/paint.png",
    tourId: "t-0",
  },
  {
    id: "ph-11",
    areaId: "f7-w",
    date: today(),
    time: "08:58",
    caption: "קומה 7 מערב – ללא צוות באתר",
    url: "/site/doorframes.png",
    tourId: "t-2",
  },
  {
    id: "ph-12",
    areaId: "b1",
    date: dayOffset(-1),
    time: "08:16",
    caption: "מרתף 1 – חניות מסומנות לצבע",
    url: "/site/earthworks.png",
    tourId: "t-1",
  },
]

/* ------------------------------------------------------------ defects ---- */

const defects: Defect[] = [
  {
    id: "d-1",
    areaId: "b2",
    date: dayOffset(-4),
    title: "רטיבות בקיר חדר משאבות",
    severity: "critical",
    status: "in_progress",
    assigneeId: "c-plumb",
    photoId: "ph-4",
    tourId: "t-0",
  },
  {
    id: "d-2",
    areaId: "f4-w",
    date: dayOffset(-3),
    title: "אריחים שקועים בדירה 405 – פינה מזרחית",
    severity: "major",
    status: "open",
    assigneeId: "c-cohen",
    tourId: "t-0",
  },
  {
    id: "d-3",
    areaId: "f2-w",
    date: dayOffset(-2),
    title: "סדק בטיח מעל חלון סלון דירה 203",
    severity: "minor",
    status: "open",
    assigneeId: "p-yossi",
  },
  {
    id: "d-4",
    areaId: "f5-e",
    date: dayOffset(-1),
    title: "נקודת חשמל שבורה בחדר שינה 504",
    severity: "major",
    status: "open",
    assigneeId: "c-elec",
    photoId: "ph-3",
    tourId: "t-1",
  },
  {
    id: "d-5",
    areaId: "g-w",
    date: dayOffset(-6),
    title: "גימור לקוי בתקרת לובי מערבי",
    severity: "minor",
    status: "fixed",
    assigneeId: "c-gypsum",
  },
  {
    id: "d-6",
    areaId: "roof",
    date: dayOffset(-2),
    title: "איטום סביב יציאת מזגן – בועות",
    severity: "major",
    status: "open",
    assigneeId: "c-plumb",
  },
]

/* ----------------------------------------------------------- blockers ---- */

const blockers: Blocker[] = [
  {
    id: "bl-1",
    areaId: "f6-w",
    date: dayOffset(-4),
    reason: "material",
    text: "חסרים משקופים לקומות 6–7 – לא ניתן להתחיל צבע",
    status: "open",
    tourId: "t-0",
    taskId: "tk-2",
    streak: 3,
  },
  {
    id: "bl-2",
    areaId: "f5-w",
    date: today(),
    reason: "manpower",
    text: "אין היום צוות חשמל בקומה 5 מערב",
    status: "open",
    tourId: "t-2",
    taskId: "tk-1",
    streak: 2,
  },
  {
    id: "bl-3",
    areaId: "facade",
    date: dayOffset(-1),
    reason: "other_contractor",
    text: "אלומיניום חזית מערבית ללא תאריך אספקה מאושר",
    status: "open",
    tourId: "t-1",
    taskId: "tk-3",
    streak: 2,
  },
  {
    id: "bl-4",
    areaId: "b3",
    date: dayOffset(-2),
    reason: "decision",
    text: "ממתין להחלטת יזם על גמר רצפת מחסנים",
    status: "open",
    taskId: "tk-9",
    streak: 1,
  },
  {
    id: "bl-5",
    areaId: "f7-e",
    date: dayOffset(-1),
    reason: "design",
    text: "אי התאמה בין תוכנית אינסטלציה לגבס בחדר רחצה 703",
    status: "open",
    taskId: "tk-12",
    streak: 1,
  },
  {
    id: "bl-6",
    areaId: "f3-w",
    date: dayOffset(-5),
    reason: "material",
    text: "חסרו דבק אריחים – נפתר, אספקה התקבלה",
    status: "resolved",
  },
]

/* -------------------------------------------------------------- tasks ---- */

const t = (task: Task): Task => task

const tasks: Task[] = [
  t({
    id: "tk-1",
    title: "לוודא כניסת צוות חשמל לקומה 5 מערב",
    description: "חשמל הצפון לא הגיע שני ימים. לתאם עם מנהל הצוות כניסה עוד היום.",
    areaId: "f5-w",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "critical",
    status: "in_progress",
    dueDate: today(),
    createdAt: dayOffset(-1),
    source: "סיור בוקר",
    tourId: "t-1",
    blockerId: "bl-2",
    history: [
      { date: dayOffset(-1), time: "08:47", text: "נוצר במהלך סיור בוקר – קומה 5 מערב" },
      { date: dayOffset(-1), time: "11:20", text: "נשלחה הודעה למנהל הצוות בחשמל הצפון" },
      { date: today(), time: "08:12", text: "בסיור הבוקר – עדיין אין צוות באזור" },
    ],
  }),
  t({
    id: "tk-2",
    title: "לאשר הזמנת משקופים לקומות 6–7",
    description: "40 משקופים. לאשר הזמנה מול דלתות ישראל ולקבל תאריך אספקה בכתב.",
    areaId: "f6-w",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "critical",
    status: "open",
    dueDate: today(),
    createdAt: dayOffset(-4),
    source: "סיור בוקר",
    tourId: "t-0",
    blockerId: "bl-1",
    history: [
      { date: dayOffset(-4), time: "08:52", text: "נוצר במהלך סיור בוקר – קומה 6 מערב" },
      { date: dayOffset(-3), time: "14:05", text: "התקבלה הצעת מחיר מדלתות ישראל" },
      { date: dayOffset(-1), time: "09:03", text: "החוסר מופיע בסיור שלישי ברציפות" },
    ],
  }),
  t({
    id: "tk-3",
    title: "לסגור עם קבלן האלומיניום תאריך סופי לחזית מערבית",
    description: "אלומיניום פסגות מתחמק מתאריך. נדרש תאריך אספקה מאושר לפני יום שני.",
    areaId: "facade",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "critical",
    status: "waiting",
    dueDate: today(),
    createdAt: dayOffset(-2),
    source: "סיכום עם קבלן",
    decisionId: "dc-2",
    blockerId: "bl-3",
    history: [
      { date: dayOffset(-2), time: "09:22", text: "נוצר מסיכום עם אלומיניום פסגות" },
      { date: dayOffset(-1), time: "16:40", text: "הקבלן ביקש לחזור אלינו לאחר בדיקת מלאי" },
    ],
  }),
  t({
    id: "tk-4",
    title: "תיקון רטיבות בחדר משאבות",
    description: "כתם רטיבות מתפשט בקיר המזרחי. לאתר מקור ולתקן לפני ריצוף.",
    areaId: "b2",
    assigneeId: "c-plumb",
    assigneeGroup: "contractor",
    priority: "critical",
    status: "in_progress",
    dueDate: today(),
    createdAt: dayOffset(-4),
    source: "סיור בוקר",
    tourId: "t-0",
    defectId: "d-1",
    photoIds: ["ph-4", "ph-5"],
    history: [
      { date: dayOffset(-4), time: "08:12", text: "נוצר במהלך סיור – זוהה ליקוי רטיבות" },
      { date: dayOffset(-3), time: "10:30", text: "הוקצה לאינסטלציה לוי" },
      { date: dayOffset(-2), time: "13:10", text: "הקבלן ביקש חומר איטום" },
      { date: dayOffset(-1), time: "08:09", text: "טרם הושלם – הכתם ללא שינוי" },
    ],
  }),
  t({
    id: "tk-5",
    title: "השלמת פנלים בדירה 502",
    areaId: "f5-w",
    assigneeId: "c-cohen",
    assigneeGroup: "contractor",
    priority: "normal",
    status: "open",
    dueDate: dayOffset(-1),
    createdAt: dayOffset(-2),
    source: "סיור בוקר",
    tourId: "t-1",
    history: [
      { date: dayOffset(-2), time: "08:50", text: "נוצר במהלך סיור בוקר – קומה 5 מערב" },
      { date: dayOffset(-1), time: "12:00", text: "הקבלן דיווח שיסיים מחר" },
    ],
  }),
  t({
    id: "tk-6",
    title: "תיקון נקודת חשמל בחדר שינה 504",
    areaId: "f5-e",
    assigneeId: "c-elec",
    assigneeGroup: "contractor",
    priority: "high",
    status: "open",
    dueDate: today(),
    createdAt: dayOffset(-1),
    source: "סיור בוקר",
    tourId: "t-1",
    defectId: "d-4",
    photoIds: ["ph-3"],
    history: [{ date: dayOffset(-1), time: "08:47", text: "נוצר במהלך סיור – ליקוי בנקודת חשמל" }],
  }),
  t({
    id: "tk-7",
    title: "סיום ריצוף דירות 401–404",
    description: "סוכם עם א. כהן שיסיים עד מחר בסוף היום.",
    areaId: "f4-e",
    assigneeId: "c-cohen",
    assigneeGroup: "contractor",
    priority: "high",
    status: "in_progress",
    dueDate: dayOffset(1),
    createdAt: dayOffset(-1),
    source: "סיכום עם קבלן",
    decisionId: "dc-1",
    photoIds: ["ph-1", "ph-2"],
    history: [
      { date: dayOffset(-1), time: "08:30", text: "נוצר מסיכום עם א. כהן ריצוף" },
      { date: today(), time: "08:31", text: "התקדמות טובה – שתי דירות הושלמו" },
    ],
  }),
  t({
    id: "tk-8",
    title: "לדאוג לאספקת 20 מ\"ר אריחים לדירה 403",
    areaId: "f4-e",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "high",
    status: "open",
    dueDate: today(),
    createdAt: dayOffset(-1),
    source: "סיכום עם קבלן",
    decisionId: "dc-1",
    history: [{ date: dayOffset(-1), time: "08:32", text: "נוצר מסיכום עם א. כהן ריצוף" }],
  }),
  t({
    id: "tk-9",
    title: "לקבל החלטת יזם על גמר רצפת מחסנים במרתף 3",
    areaId: "b3",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "normal",
    status: "waiting",
    dueDate: dayOffset(2),
    createdAt: dayOffset(-6),
    source: "סיור בוקר",
    blockerId: "bl-4",
    history: [
      { date: dayOffset(-6), time: "08:05", text: "נוצר במהלך סיור בוקר – מרתף 3" },
      { date: dayOffset(-4), time: "17:20", text: "נשלח מייל ליזם, ממתין לתשובה" },
    ],
  }),
  t({
    id: "tk-10",
    title: "פינוי פסולת בניין ממרתף 1",
    areaId: "b1",
    assigneeId: "p-ahmad",
    assigneeGroup: "team",
    priority: "normal",
    status: "open",
    dueDate: today(),
    createdAt: dayOffset(-1),
    source: "סיור בוקר",
    tourId: "t-1",
    history: [{ date: dayOffset(-1), time: "08:16", text: "נוצר במהלך סיור בוקר – מרתף 1" }],
  }),
  t({
    id: "tk-11",
    title: "סימון מיקומי גופי תאורה בלובי מזרחי",
    areaId: "g-e",
    assigneeId: "p-yossi",
    assigneeGroup: "team",
    priority: "normal",
    status: "in_progress",
    dueDate: dayOffset(1),
    createdAt: dayOffset(-2),
    source: "ידני",
    history: [{ date: dayOffset(-2), time: "15:40", text: "נוצר במשרד" }],
  }),
  t({
    id: "tk-12",
    title: "לתאם פגישת תכנון – אי התאמה אינסטלציה/גבס בחדר רחצה 703",
    areaId: "f7-e",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "high",
    status: "blocked",
    dueDate: dayOffset(1),
    createdAt: dayOffset(-1),
    source: "סיור בוקר",
    tourId: "t-1",
    blockerId: "bl-5",
    history: [
      { date: dayOffset(-1), time: "09:05", text: "נוצר במהלך סיור בוקר – קומה 7 מזרח" },
      { date: today(), time: "07:40", text: "ממתין לתשובת המתכנן" },
    ],
  }),
  t({
    id: "tk-13",
    title: "השלמת התקנת גבס במסדרון קומה 3 מזרח",
    areaId: "f3-e",
    assigneeId: "c-gypsum",
    assigneeGroup: "contractor",
    priority: "normal",
    status: "in_progress",
    dueDate: dayOffset(1),
    createdAt: dayOffset(-3),
    source: "סיור בוקר",
    photoIds: ["ph-8"],
    history: [{ date: dayOffset(-3), time: "08:38", text: "נוצר במהלך סיור בוקר" }],
  }),
  t({
    id: "tk-14",
    title: "תיקון אריחים שקועים בדירה 405",
    areaId: "f4-w",
    assigneeId: "c-cohen",
    assigneeGroup: "contractor",
    priority: "high",
    status: "open",
    dueDate: dayOffset(-2),
    createdAt: dayOffset(-3),
    source: "סיור בוקר",
    defectId: "d-2",
    history: [
      { date: dayOffset(-3), time: "08:44", text: "נוצר במהלך סיור – ליקוי ריצוף" },
      { date: dayOffset(-2), time: "09:10", text: "הקבלן אישר קבלת הליקוי" },
    ],
  }),
  t({
    id: "tk-15",
    title: "איטום חוזר סביב יציאות מזגן בגג",
    areaId: "roof",
    assigneeId: "c-plumb",
    assigneeGroup: "contractor",
    priority: "high",
    status: "open",
    dueDate: dayOffset(-1),
    createdAt: dayOffset(-2),
    source: "סיור בוקר",
    defectId: "d-6",
    history: [{ date: dayOffset(-2), time: "08:58", text: "נוצר במהלך סיור בוקר – גג" }],
  }),
  t({
    id: "tk-16",
    title: "בדיקת לחצי מים בקולטנים – מרתף 2",
    areaId: "b2",
    assigneeId: "c-plumb",
    assigneeGroup: "contractor",
    priority: "normal",
    status: "waiting",
    dueDate: dayOffset(2),
    createdAt: dayOffset(-2),
    source: "ידני",
    history: [{ date: dayOffset(-2), time: "16:10", text: "נוצר במשרד" }],
  }),
  t({
    id: "tk-17",
    title: "צבע יסוד לדירות 201–204",
    areaId: "f2-e",
    assigneeId: "c-paint",
    assigneeGroup: "contractor",
    priority: "normal",
    status: "in_progress",
    dueDate: dayOffset(2),
    createdAt: dayOffset(-2),
    source: "סיור בוקר",
    photoIds: ["ph-10"],
    history: [{ date: dayOffset(-2), time: "08:20", text: "נוצר במהלך סיור בוקר" }],
  }),
  t({
    id: "tk-18",
    title: "תיקון סדק טיח מעל חלון סלון 203",
    areaId: "f2-w",
    assigneeId: "p-david",
    assigneeGroup: "team",
    priority: "low",
    status: "open",
    dueDate: dayOffset(3),
    createdAt: dayOffset(-2),
    source: "סיור בוקר",
    defectId: "d-3",
    history: [{ date: dayOffset(-2), time: "08:36", text: "נוצר במהלך סיור בוקר" }],
  }),
  t({
    id: "tk-19",
    title: "תיאום מנוף לאספקת אלומיניום – חזית מערבית",
    areaId: "facade",
    assigneeId: "p-yossi",
    assigneeGroup: "team",
    priority: "high",
    status: "open",
    dueDate: dayOffset(3),
    createdAt: dayOffset(-1),
    source: "סיכום עם קבלן",
    decisionId: "dc-2",
    history: [{ date: dayOffset(-1), time: "09:24", text: "נוצר מסיכום עם אלומיניום פסגות" }],
  }),
  t({
    id: "tk-20",
    title: "השלמת אבני שפה בשביל הכניסה הראשי",
    areaId: "ext",
    assigneeId: "p-yossi",
    assigneeGroup: "team",
    priority: "normal",
    status: "in_progress",
    dueDate: dayOffset(4),
    createdAt: dayOffset(-1),
    source: "סיור בוקר",
    photoIds: ["ph-9"],
    history: [{ date: dayOffset(-1), time: "09:28", text: "נוצר במהלך סיור בוקר – פיתוח חוץ" }],
  }),
  t({
    id: "tk-21",
    title: "להזמין בדיקת מעבדה לבטון תקרת קומה 7",
    areaId: "f7-w",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "normal",
    status: "open",
    dueDate: dayOffset(3),
    createdAt: dayOffset(-5),
    source: "ידני",
    history: [{ date: dayOffset(-5), time: "11:00", text: "נוצר במשרד" }],
  }),
  t({
    id: "tk-22",
    title: "השלמת נקודות חשמל בקומה 6 מזרח",
    areaId: "f6-e",
    assigneeId: "c-elec",
    assigneeGroup: "contractor",
    priority: "high",
    status: "open",
    dueDate: dayOffset(-3),
    createdAt: dayOffset(-7),
    source: "סיור בוקר",
    history: [
      { date: dayOffset(-7), time: "08:41", text: "נוצר במהלך סיור בוקר" },
      { date: dayOffset(-5), time: "10:15", text: "הקבלן התחייב לסיים עד אמצע השבוע" },
      { date: dayOffset(-3), time: "08:44", text: "טרם הושלם" },
    ],
  }),
  t({
    id: "tk-23",
    title: "ניקיון גמר לובי מערבי לקראת ביקור יזם",
    areaId: "g-w",
    assigneeId: "p-ahmad",
    assigneeGroup: "team",
    priority: "normal",
    status: "done",
    dueDate: dayOffset(-1),
    createdAt: dayOffset(-3),
    completedAt: dayOffset(-1),
    source: "ידני",
    history: [
      { date: dayOffset(-3), time: "12:20", text: "נוצר במשרד" },
      { date: dayOffset(-1), time: "15:30", text: "הושלם" },
    ],
  }),
  t({
    id: "tk-24",
    title: "תיקון גימור תקרת לובי מערבי",
    areaId: "g-w",
    assigneeId: "c-gypsum",
    assigneeGroup: "contractor",
    priority: "normal",
    status: "done",
    dueDate: dayOffset(-2),
    createdAt: dayOffset(-6),
    completedAt: dayOffset(-2),
    source: "סיור בוקר",
    defectId: "d-5",
    history: [
      { date: dayOffset(-6), time: "08:29", text: "נוצר במהלך סיור בוקר" },
      { date: dayOffset(-2), time: "14:00", text: "הושלם ואושר בסיור" },
    ],
  }),
  t({
    id: "tk-25",
    title: "אספקת דבק אריחים לקומה 3 מערב",
    areaId: "f3-w",
    assigneeId: "me",
    assigneeGroup: "me",
    priority: "high",
    status: "done",
    dueDate: dayOffset(-4),
    createdAt: dayOffset(-5),
    completedAt: dayOffset(-4),
    source: "סיור בוקר",
    history: [
      { date: dayOffset(-5), time: "08:33", text: "נוצר במהלך סיור בוקר" },
      { date: dayOffset(-4), time: "09:50", text: "האספקה הגיעה לאתר – הושלם" },
    ],
  }),
  t({
    id: "tk-26",
    title: "החלפת גופי תאורה זמניים במרתף 3",
    areaId: "b3",
    assigneeId: "p-david",
    assigneeGroup: "team",
    priority: "low",
    status: "done",
    dueDate: dayOffset(-2),
    createdAt: dayOffset(-4),
    completedAt: dayOffset(-2),
    source: "ידני",
    history: [{ date: dayOffset(-2), time: "13:15", text: "הושלם" }],
  }),
  t({
    id: "tk-27",
    title: "לוודא שילוט בטיחות בכל קומה",
    areaId: null,
    assigneeId: "p-yossi",
    assigneeGroup: "team",
    priority: "normal",
    status: "open",
    dueDate: dayOffset(1),
    createdAt: dayOffset(-2),
    source: "ידני",
    history: [{ date: dayOffset(-2), time: "09:00", text: "נוצר במשרד" }],
  }),
]

/* ---------------------------------------------------------- decisions ---- */

const decisions: Decision[] = [
  {
    id: "dc-1",
    areaId: "f4-e",
    date: dayOffset(-1),
    time: "08:30",
    contractorId: "c-cohen",
    myRequirement: "לסיים ריצוף דירות 401–404",
    theirRequirement: 'אספקת 20 מ"ר אריחים לדירה 403',
    commitment: "סיום עד מחר בסוף היום",
    dueDate: dayOffset(1),
    notes: "הקבלן מכניס צוות נוסף של שני רצפים.",
    taskIds: ["tk-7", "tk-8"],
    tourId: "t-1",
  },
  {
    id: "dc-2",
    areaId: "facade",
    date: dayOffset(-2),
    time: "09:22",
    contractorId: "c-alum",
    myRequirement: "תאריך אספקה מאושר לחזית מערבית",
    theirRequirement: "תיאום מנוף ליום האספקה",
    commitment: "תשובה סופית עד יום ראשון",
    dueDate: dayOffset(2),
    notes: "אם לא יתקבל תאריך – נדרש לבחון ספק חלופי.",
    taskIds: ["tk-3", "tk-19"],
  },
  {
    id: "dc-3",
    areaId: "f6-w",
    date: dayOffset(-3),
    time: "08:55",
    contractorId: "c-doors",
    myRequirement: "אספקת 40 משקופים לקומות 6–7",
    theirRequirement: "אישור הזמנה חתום",
    commitment: "אספקה תוך 5 ימי עסקים מאישור",
    dueDate: dayOffset(2),
    taskIds: ["tk-2"],
  },
  {
    id: "dc-4",
    areaId: "f5-w",
    date: dayOffset(-1),
    time: "08:49",
    contractorId: "c-elec",
    myRequirement: "צוות של 3 חשמלאים בקומה 5 מערב",
    theirRequirement: "גישה חופשית לקומה ללא צוות ריצוף",
    commitment: "כניסת צוות מחר בבוקר",
    dueDate: today(),
    notes: "הקבלן טוען לעומס בפרויקט אחר.",
    taskIds: ["tk-1"],
    tourId: "t-1",
  },
]

/* ------------------------------------------------------- observations ---- */

const observations: Observation[] = [
  {
    id: "ob-1",
    tourId: "t-1",
    areaId: "f5-w",
    date: dayOffset(-1),
    time: "08:47",
    kind: "activity",
    text: "אין צוות חשמל בקומה. הריצוף לא יכול להתקדם ללא סיום נקודות.",
  },
  {
    id: "ob-2",
    tourId: "t-1",
    areaId: "f4-e",
    date: dayOffset(-1),
    time: "08:30",
    kind: "progress",
    text: "ריצוף מתקדם היטב – שתי דירות הושלמו מאז אתמול.",
  },
  {
    id: "ob-3",
    tourId: "t-1",
    areaId: "f6-w",
    date: dayOffset(-1),
    time: "08:52",
    kind: "note",
    text: "פתחי הדלתות ללא משקופים. הצבעים לא יכולים להיכנס.",
  },
  {
    id: "ob-4",
    tourId: "t-1",
    areaId: "facade",
    date: dayOffset(-1),
    time: "09:15",
    kind: "voice",
    text: "קבלן האלומיניום לא הגיע לפגישה. החזית המערבית פתוחה לחלוטין, זה מסכן את הגמר בקומות 3–5.",
  },
  {
    id: "ob-5",
    tourId: "t-0",
    areaId: "b2",
    date: dayOffset(-4),
    time: "08:12",
    kind: "note",
    text: "רטיבות בחדר משאבות – נראה שמקורה בקולטן.",
  },
  {
    id: "ob-6",
    tourId: "t-1",
    areaId: "ext",
    date: dayOffset(-1),
    time: "09:28",
    kind: "progress",
    text: "פיתוח חוץ התחיל השבוע – אבני שפה בשביל הכניסה.",
  },
  {
    id: "ob-7",
    tourId: "t-0",
    areaId: "f3-e",
    date: dayOffset(-2),
    time: "08:38",
    kind: "progress",
    text: "גבס מתקדם במסדרון, צוות של 4 עובדים.",
  },
  {
    id: "ob-8",
    tourId: "t-1",
    areaId: "f7-w",
    date: dayOffset(-1),
    time: "09:02",
    kind: "activity",
    text: "אין פעילות בקומה 7 מערב שלישי ברציפות.",
  },
]

/* -------------------------------------------------------------- tours ---- */

function emptyVisit(areaId: string): AreaVisit {
  return {
    areaId,
    visitedAt: null,
    skipped: false,
    activeToday: null,
    teamIds: [],
    workersCount: null,
    progressTags: [],
    progressNote: "",
    observationIds: [],
    taskIds: [],
    blockerIds: [],
    defectIds: [],
    decisionIds: [],
    photoIds: [],
  }
}

function seedTours(areas: Area[]): Tour[] {
  const route = areas.map((a) => a.id)

  const historical = (id: string, date: string): Tour => ({
    id,
    date,
    startedAt: "08:02",
    endedAt: "09:11",
    status: "done",
    routeAreaIds: route,
    visits: {},
    topPriorities: [],
  })

  const t0 = historical("t-0", dayOffset(-4))
  const t1 = historical("t-1", dayOffset(-1))
  t1.topPriorities = ["tk-1", "tk-2", "tk-3"]

  const todayTour: Tour = {
    id: "t-2",
    date: today(),
    startedAt: null,
    endedAt: null,
    status: "planned",
    routeAreaIds: route,
    visits: Object.fromEntries(route.map((id) => [id, emptyVisit(id)])),
    topPriorities: [],
  }
  return [t0, t1, todayTour]
}

/* ----------------------------------------------------------- activity ---- */

const activity: ActivityLog[] = [
  {
    id: "ac-1",
    date: today(),
    time: "07:15",
    kind: "tour",
    text: "יום עבודה נפתח – 6 קבלנים מדווחים הגעה",
  },
  {
    id: "ac-2",
    date: today(),
    time: "07:42",
    kind: "task_status",
    text: 'תיקון רטיבות בחדר משאבות עודכן ל"בטיפול"',
    areaId: "b2",
    personId: "c-plumb",
    refId: "tk-4",
  },
  {
    id: "ac-3",
    date: today(),
    time: "07:55",
    kind: "blocker",
    text: "חשמל הצפון עדכן שלא ייכנס לקומה 5 מערב לפני 10:00",
    areaId: "f5-w",
    personId: "c-elec",
    refId: "bl-2",
  },
  {
    id: "ac-4",
    date: today(),
    time: "08:31",
    kind: "photo",
    text: "תמונה נוספה – ריצוף דירה 402",
    areaId: "f4-e",
    refId: "ph-2",
  },
  {
    id: "ac-5",
    date: dayOffset(-1),
    time: "09:11",
    kind: "tour",
    text: "סיור בוקר הושלם – 22 אזורים, 8 משימות חדשות",
  },
  {
    id: "ac-6",
    date: dayOffset(-1),
    time: "16:40",
    kind: "task_status",
    text: "אלומיניום פסגות ביקש לחזור אלינו לאחר בדיקת מלאי",
    areaId: "facade",
    personId: "c-alum",
    refId: "tk-3",
  },
]

/* -------------------------------------------------------- initial state -- */

export function createSeedState(): ProjectState {
  const areas = buildAreas()
  return {
    project: {
      name: "פרויקט הרקפות",
      apartments: 45,
      basements: 3,
      floors: 7,
      startedAt: dayOffset(-420),
    },
    areas,
    people,
    tasks,
    observations,
    blockers,
    defects,
    decisions,
    photos,
    tours: seedTours(areas),
    activity,
    dayTargets: [
      { id: "dt-1", text: "לוודא כניסת צוות חשמל לקומה 5 מערב", taskId: "tk-1", done: false, date: today() },
      { id: "dt-2", text: "לאשר הזמנת משקופים לקומות 6–7", taskId: "tk-2", done: false, date: today() },
      {
        id: "dt-3",
        text: "לסגור עם קבלן האלומיניום תאריך סופי לחזית מערבית",
        taskId: "tk-3",
        done: false,
        date: today(),
      },
    ],
    offline: false,
    pendingCount: 0,
    lastSyncAt: "07:12",
  }
}

export { emptyVisit }
